language: python
python:
  - "2.7"
language: python
script: travis_wait 30 pytest tests/
before_install: 
  - sudo apt-get install -y python-pyaudio python3-pyaudio portaudio19-dev
install:
  - pip install -r requirements.txt
