language: python
python:
  - "2.7"
install: pip install -r requirements.txt
language: python
script: travis_wait 30 python -m pytest tests/
before_install:
  - sudo apt-get install -y python-pyaudio python3-pyaudio
